### ISSUE TITLE
How to install the align?

### ISSUE THREAD

**Issue by mochechan** [zeusees/License-Plate-Detector#14]
An align has been imported in your code. How to install the align?
`from align import *`

https://github.com/zeusees/Mobilenet-SSD-License-Plate-Detection/blob/master/detect_opencv.py#L5

I tried the following command without success.
`pip install align`

**Comment by a243845305** [comment]
> An align has been imported in your code. How to install the align?
> `from align import *`
> 
> https://github.com/zeusees/Mobilenet-SSD-License-Plate-Detection/blob/master/detect_opencv.py#L5
> 
> I tried the following command without success.
> `pip install align`

Please put your error log in here.

**Comment by alezsd** [comment]
pip3 install --user align
and all dependencies.
Try move files mssd512_voc.* to tmp folder
In the code change the folderk variable to images folder
I tried and it works!
