### ISSUE TITLE
get zero-value output when I use ‘lpr’ model

### ISSUE THREAD

**Issue by FanglaiPeng** [zeusees/License-Plate-Detector#15]
hi, I dont have a Caffe environment so I use opencv.dnn to load lpr caffemodel, but the output of forward inference is all ZERO(_out = net.forward()_), however, the last but one layer(_mbox_loc, mbox_priorbox, mbox_conf_flattern_) get non-zero value. I have no idea about this, could you do me a favor and guide me to run this project successfully? thanks!
BTW, my PC envs: _Anaconda3 with python3.7, opencv4.1.1_
![123](https://user-images.githubusercontent.com/14259448/67667667-3fff5c80-f9a9-11e9-855c-6566e802b484.jpg)

**Comment by netdrop-sys** [comment]
please try our new detect model.
