### ISSUE TITLE
ncnn模型精度比pytorch低很多

### ISSUE THREAD

**Issue by FanglaiPeng** [zeusees/License-Plate-Detector#20]
pytorch版大部分可以检测，ncnn版效果没那么好，尝试了不同阈值还是达不到pytorch版的效果，请问是pytorch->onnx->ncnn吗？

**Comment by netdrop-sys** [comment]
是的，转换的过程中有精度损失，目前没什么好的办法。

**Comment by FanglaiPeng** [comment]
自己重新转换调整了部分参数，效果好很多啦。ncnn模型我放下面了，感谢大佬的原版模型。
[mnet_plate_opt.zip](https://github.com/zeusees/License-Plate-Detector/files/5601542/mnet_plate_opt.zip)

**Comment by netdrop-sys** [comment]
@FanglaiPeng  如果调整的可否告知一下，我们后续也好继续完善。

**Comment by FanglaiPeng** [comment]
主要是ncnn interp的问题，1x64x20x23 upsample到1x64x40x45，width_scale应该是1.956522e+00，但是ncnn计算结果是2.000000e+00
最新版ncnn已经fix了。

**Comment by zhongwenkun886** [comment]
用 mnet_plate_opt 测试，图片 2.jpg 会崩溃，还有好些图片（11.jpg、12.jpg、13.jpg）检测不出来。

**Comment by FanglaiPeng** [comment]
Try new ncnn model below.
When conducting pytorch2onnx2onnxsim2ncnn, interp scale depends on the input data shape, which should be integer in general, for instance "2" in this case. However, I set interp scale 1.95 before as my test data shape is 720x640x3. That's a lazy behavior. The common approach to get ncnn model from this pytorch model: a.) set proper input data shape to ensure interp scale is 2. b.) add "crop" layer to create "real" shape blob.
ref. [](https://pytorch.apachecn.org/docs/0.3/onnx.html)
[mnet_plate_sim_opt.zip](https://github.com/zeusees/License-Plate-Detector/files/5740323/mnet_plate_sim_opt.zip)

**Comment by zhongwenkun886** [comment]
Good!

**Comment by zhongwenkun886** [comment]
> 
> 
> Try new ncnn model below.
> When conducting pytorch2onnx2onnxsim2ncnn, interp scale depends on the input data shape, which should be integer in general, for instance "2" in this case. However, I set interp scale 1.95 before as my test data shape is 720x640x3. That's a lazy behavior. The common approach to get ncnn model from this pytorch model: a.) set proper input data shape to ensure interp scale is 2. b.) add "crop" layer to create "real" shape blob. Just like RetinaFace-MobileNet.
> [ref.]
> https://pytorch.apachecn.org/docs/0.3/onnx.html
> https://github.com/deepinsight/insightface/tree/master/detection/RetinaFace
> [model]
> [mnet_plate_sim_opt.zip](https://github.com/zeusees/License-Plate-Detector/files/5740323/mnet_plate_sim_opt.zip)
hi ,FanglaiPeng ,can you share your converting code and processing way？ I want to convert the model to MNN model.

**Comment by zhongwenkun886** [comment]
hi ,FanglaiPeng ,can you share your converting code and processing way？ I want to convert the model to MNN model.
