### ISSUE TITLE
final loss

### ISSUE THREAD

**Issue by singal95** [zeusees/License-Plate-Detector#23]
can you share the final loss when, i found it large, just give me a reference, such as loc: 0.xxx, cla: 0.xx, landms 0.xx
or loc: 0.00x cla: 0.00x, landms: 0.00x

**Comment by netdrop-sys** [comment]
loc: 0.04xx, cla: 0.25x,landm 0.2xx

**Comment by singal95** [comment]
> loc: 0.04xx, cla: 0.25x,landm 0.2xx

thanks
