### ISSUE TITLE
大佬看你支持很多种车牌类型的,可以分享下您的数据收集思路吗

### ISSUE THREAD

**Issue by L-lei** [zeusees/License-Plate-Detector#26]
看您支持,以下的车牌;
蓝色单层车牌
黄色单层车牌
绿色新能源车牌、民航车牌
黑色单层车牌
白色警牌、军牌、武警车牌
黄色双层车牌
绿色农用车牌
白色双层军牌

如直接搜索"白色警牌或者白色军牌"等,几十张都很难收集,更别说用于训练,可以分享下您是如何收集这些数据的数据思路吗,有什么技巧呢,GAN?

**Comment by Jinkham** [comment]
自己生成一部分，网上下载一部分，还有一些是群里大佬提供的。

**Comment by L-lei** [comment]
多谢
