### ISSUE TITLE
不同图片为什么检测时间相差这么大，有的需要几秒，有的只需要几十毫秒？

### ISSUE THREAD

**Issue by GitHubLuGeng** [zeusees/License-Plate-Detector#27]
### 打印的识别日志：
./imgs/19.jpg
net forward time: 4.2881
priorBox time: 4.3867
0.9999
0 -1
164 50
5 60
169 110
./imgs/1.jpg
net forward time: 0.0079
priorBox time: 0.0723
0.9998
-1 0
135 4
4 52
139 57
./imgs/9.jpg
net forward time: 2.2308
priorBox time: 2.2579
0.9443
-1 0
109 0
-1 32
108 32

**Comment by GradientDescentEX** [comment]
我也遇到了同样的问题，应该是图片太大了

**Comment by Jinkham** [comment]
anchor在不同尺寸图片，计算过程不同，如果输入图片尺寸一致的话，只需要计算一次即可。
