### ISSUE TITLE
树莓派编译链接时报错

### ISSUE THREAD

**Issue by byronxu89** [zeusees/License-Plate-Detector#30]
[100%] Linking CXX executable LPDetector
/usr/bin/ld: CMakeFiles/LPDetector.dir/LPDetector.cpp.o: in function `Detector::Detector()':
LPDetector.cpp:(.text+0x5c): undefined reference to `ncnn::Net::Net()'
/usr/bin/ld: CMakeFiles/LPDetector.dir/LPDetector.cpp.o: in function `Detector::Detector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
LPDetector.cpp:(.text+0xfc): undefined reference to `ncnn::Net::Net()'
/usr/bin/ld: CMakeFiles/LPDetector.dir/LPDetector.cpp.o: in function `Detector::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
LPDetector.cpp:(.text+0x178): undefined reference to `ncnn::Net::load_param(char const*)'
/usr/bin/ld: LPDetector.cpp:(.text+0x1a0): undefined reference to `ncnn::Net::load_model(char const*)'
/usr/bin/ld: CMakeFiles/LPDetector.dir/LPDetector.cpp.o: in function `Detector::Detect(cv::Mat&, std::vector<bbox, std::allocator<bbox> >&)':
LPDetector.cpp:(.text+0x23c): undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int, ncnn::Allocator*)'
/usr/bin/ld: LPDetector.cpp:(.text+0x254): undefined reference to `ncnn::Mat::substract_mean_normalize(float const*, float const*)'
/usr/bin/ld: LPDetector.cpp:(.text+0x2c4): undefined reference to `ncnn::Net::create_extractor() const'
/usr/bin/ld: LPDetector.cpp:(.text+0x2d4): undefined reference to `ncnn::Extractor::set_light_mode(bool)'
/usr/bin/ld: LPDetector.cpp:(.text+0x2e4): undefined reference to `ncnn::Extractor::set_num_threads(int)'
/usr/bin/ld: LPDetector.cpp:(.text+0x2f8): undefined reference to `ncnn::Extractor::input(int, ncnn::Mat const&)'
/usr/bin/ld: LPDetector.cpp:(.text+0x330): undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&)'
/usr/bin/ld: LPDetector.cpp:(.text+0x344): undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&)'
/usr/bin/ld: LPDetector.cpp:(.text+0x358): undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&)'
/usr/bin/ld: CMakeFiles/LPDetector.dir/LPDetector.cpp.o: in function `Detector::Release()':
LPDetector.cpp:(.text._ZN8Detector7ReleaseEv[_ZN8Detector7ReleaseEv]+0x34): undefined reference to `ncnn::Net::~Net()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/LPDetector.dir/build.make:106: LPDetector] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/LPDetector.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Jinkham** [comment]
ncnn没有编译正确
