### ISSUE TITLE
what version of caffe that could generate Mobilenet-SSD?

### ISSUE THREAD

**Issue by JimmyLauren** [zeusees/License-Plate-Detector#8]
Hi, i was doing research on car plate recognition recently. i downloaded the program but i couldn't find the caffe version that could compile Mobilenet-SSD suitable for this project. What is the version of caffe did you use?

**Comment by paul5634** [comment]
you could use this repo： [https://github.com/chuanqi305/ssd](url)
this is a 3rd party caffe that support ssd
